[2024-01-22T22:11:16.222+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:11:16.226+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:11:16.227+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-01-22T22:11:16.234+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): test> on 2022-05-28 00:00:00+00:00
[2024-01-22T22:11:16.239+0000] {standard_task_runner.py:57} INFO - Started process 114 to run task
[2024-01-22T22:11:16.243+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpqmtfigc8']
[2024-01-22T22:11:16.247+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask test
[2024-01-22T22:11:16.283+0000] {task_command.py:416} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [running]> on host 19955daf03c7
[2024-01-22T22:11:16.327+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-28T00:00:00+00:00'
[2024-01-22T22:11:16.335+0000] {spark_submit.py:236} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-01-22T22:11:16.335+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py
[2024-01-22T22:11:16.352+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 71: /usr/lib/jvm/java-8-openjdk-amd64//bin/java: No such file or directory
[2024-01-22T22:11:16.353+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 96: CMD: bad array subscript
[2024-01-22T22:11:16.363+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 467, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py. Error code is: 1.
[2024-01-22T22:11:16.365+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_sample_dag, task_id=test, execution_date=20220528T000000, start_date=20240122T221116, end_date=20240122T221116
[2024-01-22T22:11:16.371+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task test (Cannot execute: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py. Error code is: 1.; 114)
[2024-01-22T22:11:16.419+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-22T22:11:16.434+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
