[2024-01-22T22:11:01.543+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:11:01.547+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:11:01.547+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-22T22:11:01.553+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): test> on 2022-05-28 00:00:00+00:00
[2024-01-22T22:11:01.556+0000] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2024-01-22T22:11:01.559+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmplvge3x1t']
[2024-01-22T22:11:01.563+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask test
[2024-01-22T22:11:01.593+0000] {task_command.py:416} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [running]> on host 19955daf03c7
[2024-01-22T22:11:01.634+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-28T00:00:00+00:00'
[2024-01-22T22:11:01.640+0000] {spark_submit.py:236} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-01-22T22:11:01.641+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py
[2024-01-22T22:11:01.656+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 71: /usr/lib/jvm/java-8-openjdk-amd64//bin/java: No such file or directory
[2024-01-22T22:11:01.657+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 96: CMD: bad array subscript
[2024-01-22T22:11:01.667+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 467, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py. Error code is: 1.
[2024-01-22T22:11:01.669+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_sample_dag, task_id=test, execution_date=20220528T000000, start_date=20240122T221101, end_date=20240122T221101
[2024-01-22T22:11:01.676+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task test (Cannot execute: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py. Error code is: 1.; 101)
[2024-01-22T22:11:01.691+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-22T22:11:01.713+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-22T22:27:36.074+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:27:36.082+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:27:36.083+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-22T22:27:36.091+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): test> on 2022-05-28 00:00:00+00:00
[2024-01-22T22:27:36.101+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2024-01-22T22:27:36.107+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp7g1h3r5b']
[2024-01-22T22:27:36.111+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask test
[2024-01-22T22:27:36.161+0000] {task_command.py:416} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [running]> on host 47d39f67dfe9
[2024-01-22T22:27:36.226+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-28T00:00:00+00:00'
[2024-01-22T22:27:36.241+0000] {spark_submit.py:236} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-01-22T22:27:36.247+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py
[2024-01-22T22:27:36.292+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 71: /usr/lib/jvm/java-8-openjdk-amd64//bin/java: No such file or directory
[2024-01-22T22:27:36.293+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 96: CMD: bad array subscript
[2024-01-22T22:27:36.308+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 467, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py. Error code is: 1.
[2024-01-22T22:27:36.310+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_sample_dag, task_id=test, execution_date=20220528T000000, start_date=20240122T222736, end_date=20240122T222736
[2024-01-22T22:27:36.320+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task test (Cannot execute: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py. Error code is: 1.; 75)
[2024-01-22T22:27:36.362+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-22T22:27:36.380+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-22T22:38:36.298+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:38:36.303+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:38:36.303+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-22T22:38:36.310+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): test> on 2022-05-28 00:00:00+00:00
[2024-01-22T22:38:36.314+0000] {standard_task_runner.py:57} INFO - Started process 69 to run task
[2024-01-22T22:38:36.319+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp8oqi4xvm']
[2024-01-22T22:38:36.322+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask test
[2024-01-22T22:38:36.369+0000] {task_command.py:416} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [running]> on host 3441088a5e19
[2024-01-22T22:38:36.426+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-28T00:00:00+00:00'
[2024-01-22T22:38:36.436+0000] {spark_submit.py:236} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-01-22T22:38:36.437+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py
[2024-01-22T22:38:36.459+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 71: /usr/lib/jvm/java-8-openjdk-amd64//bin/java: No such file or directory
[2024-01-22T22:38:36.460+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 96: CMD: bad array subscript
[2024-01-22T22:38:36.473+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 467, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py. Error code is: 1.
[2024-01-22T22:38:36.476+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_sample_dag, task_id=test, execution_date=20220528T000000, start_date=20240122T223836, end_date=20240122T223836
[2024-01-22T22:38:36.484+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task test (Cannot execute: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py. Error code is: 1.; 69)
[2024-01-22T22:38:36.529+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-22T22:38:36.544+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-22T22:48:09.200+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:48:09.211+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:48:09.211+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-22T22:48:09.218+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): test> on 2022-05-28 00:00:00+00:00
[2024-01-22T22:48:09.224+0000] {standard_task_runner.py:57} INFO - Started process 96 to run task
[2024-01-22T22:48:09.227+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp5g_22wky']
[2024-01-22T22:48:09.230+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask test
[2024-01-22T22:48:09.280+0000] {task_command.py:416} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [running]> on host 9c1ad29dcd9c
[2024-01-22T22:48:09.359+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-28T00:00:00+00:00'
[2024-01-22T22:48:09.368+0000] {spark_submit.py:236} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-01-22T22:48:09.369+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /user/local/spark/app/spark.py
[2024-01-22T22:48:15.202+0000] {spark_submit.py:536} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-01-22T22:48:15.209+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-01-22T22:48:15.214+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-01-22T22:48:15.221+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-01-22T22:48:15.222+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-01-22T22:48:15.223+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-01-22T22:48:15.223+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-01-22T22:48:15.224+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-01-22T22:48:15.224+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-01-22T22:48:15.225+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-01-22T22:48:15.225+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-22T22:48:15.377+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-22T22:48:15.543+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-22T22:53:28.725+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:53:28.730+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T22:53:28.730+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-22T22:53:28.740+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): test> on 2022-05-28 00:00:00+00:00
[2024-01-22T22:53:28.746+0000] {standard_task_runner.py:57} INFO - Started process 76 to run task
[2024-01-22T22:53:28.754+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmppnad0qt2']
[2024-01-22T22:53:28.757+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask test
[2024-01-22T22:53:28.913+0000] {task_command.py:416} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [running]> on host 3b2231e5c840
[2024-01-22T22:53:29.005+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-28T00:00:00+00:00'
[2024-01-22T22:53:29.015+0000] {spark_submit.py:236} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-01-22T22:53:29.016+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /user/local/spark/app/spark.py
[2024-01-22T22:53:31.170+0000] {spark_submit.py:536} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-01-22T22:53:31.173+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-01-22T22:53:31.175+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-01-22T22:53:31.175+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-01-22T22:53:31.175+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-01-22T22:53:31.176+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-01-22T22:53:31.177+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-01-22T22:53:31.177+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-01-22T22:53:31.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-01-22T22:53:31.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-01-22T22:53:31.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-22T22:53:31.216+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 467, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /user/local/spark/app/spark.py. Error code is: 1.
[2024-01-22T22:53:31.224+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_sample_dag, task_id=test, execution_date=20220528T000000, start_date=20240122T225328, end_date=20240122T225331
[2024-01-22T22:53:31.241+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task test (Cannot execute: spark-submit --master yarn --name arrow-spark /user/local/spark/app/spark.py. Error code is: 1.; 76)
[2024-01-22T22:53:31.276+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-22T22:53:31.300+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-22T23:07:38.044+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-01-22T23:07:38.046+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2024-01-22T23:12:53.555+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [skipped]>, dependency 'Task Instance State' FAILED: Task is in the 'skipped' state.
[2024-01-22T23:12:53.559+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
